name: Build and Deploy
on: 
    push:        

jobs:
  detect-environment:
    uses: mad81github/helloworldjs-fork/.github/workflows/detectEnvWF.yml@main
    with:
      branch: ${{github.ref}}    
  build:
    runs-on: ubuntu-latest
    needs: [detect-environment]
    outputs:
        artifact_name: ${{ steps.build.outputs.artifact_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: BuildAPP
        uses: ./.github/actions/build
        id: build
        with:
            base_path: 'sample-app'            
     
 # build:
 #   uses: mad81github/helloworldjs-fork/.github/workflows/buildWF.yml@main
 #   with:
 #     base_path: 'sample-app'


  deploy:
   needs: [build,detect-environment]
   uses: mad81github/helloworldjs-fork/.github/workflows/deployWF.yml@main
   with:
     env: ${{needs.detect-environment.outputs.environment}}
     artifact_name: ${{needs.build.outputs.artifact_name}}